# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-08 19:38
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('niji', '0002_auto_20160126_1209'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('use_gravatar', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, default='', max_length=255, upload_to='uploads/forum/avatars/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='forum_avatar', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
