# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-26 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='niji.Topic'),
        ),
    ]
