# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-20 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('niji', '0004_auto_20160628_0609'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='closed',
            field=models.BooleanField(default=False),
        ),
    ]
